// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vpn_service.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientStatus int32

const (
	ClientStatus_EXPIRED ClientStatus = 0
	ClientStatus_VALID   ClientStatus = 1
	ClientStatus_REVOKED ClientStatus = 2
)

var ClientStatus_name = map[int32]string{
	0: "EXPIRED",
	1: "VALID",
	2: "REVOKED",
}

var ClientStatus_value = map[string]int32{
	"EXPIRED": 0,
	"VALID":   1,
	"REVOKED": 2,
}

func (x ClientStatus) String() string {
	return proto.EnumName(ClientStatus_name, int32(x))
}

func (ClientStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{0}
}

// MARK: disconnect request/response
type DisconnectRequest struct {
	Client               string   `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectRequest) Reset()         { *m = DisconnectRequest{} }
func (m *DisconnectRequest) String() string { return proto.CompactTextString(m) }
func (*DisconnectRequest) ProtoMessage()    {}
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{0}
}

func (m *DisconnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectRequest.Unmarshal(m, b)
}
func (m *DisconnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectRequest.Marshal(b, m, deterministic)
}
func (m *DisconnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectRequest.Merge(m, src)
}
func (m *DisconnectRequest) XXX_Size() int {
	return xxx_messageInfo_DisconnectRequest.Size(m)
}
func (m *DisconnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectRequest proto.InternalMessageInfo

func (m *DisconnectRequest) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

type DisconnectResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectResponse) Reset()         { *m = DisconnectResponse{} }
func (m *DisconnectResponse) String() string { return proto.CompactTextString(m) }
func (*DisconnectResponse) ProtoMessage()    {}
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{1}
}

func (m *DisconnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectResponse.Unmarshal(m, b)
}
func (m *DisconnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectResponse.Marshal(b, m, deterministic)
}
func (m *DisconnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectResponse.Merge(m, src)
}
func (m *DisconnectResponse) XXX_Size() int {
	return xxx_messageInfo_DisconnectResponse.Size(m)
}
func (m *DisconnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectResponse proto.InternalMessageInfo

func (m *DisconnectResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// MARK: list allocations request/response
type ListAllocationsRequest struct {
	Client               string   `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	OnlyAllocated        bool     `protobuf:"varint,2,opt,name=only_allocated,json=onlyAllocated,proto3" json:"only_allocated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAllocationsRequest) Reset()         { *m = ListAllocationsRequest{} }
func (m *ListAllocationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAllocationsRequest) ProtoMessage()    {}
func (*ListAllocationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{2}
}

func (m *ListAllocationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAllocationsRequest.Unmarshal(m, b)
}
func (m *ListAllocationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAllocationsRequest.Marshal(b, m, deterministic)
}
func (m *ListAllocationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAllocationsRequest.Merge(m, src)
}
func (m *ListAllocationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAllocationsRequest.Size(m)
}
func (m *ListAllocationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAllocationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAllocationsRequest proto.InternalMessageInfo

func (m *ListAllocationsRequest) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *ListAllocationsRequest) GetOnlyAllocated() bool {
	if m != nil {
		return m.OnlyAllocated
	}
	return false
}

type ListAllocationsResponse struct {
	Allocations          []*Allocation `protobuf:"bytes,1,rep,name=allocations,proto3" json:"allocations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListAllocationsResponse) Reset()         { *m = ListAllocationsResponse{} }
func (m *ListAllocationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAllocationsResponse) ProtoMessage()    {}
func (*ListAllocationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{3}
}

func (m *ListAllocationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAllocationsResponse.Unmarshal(m, b)
}
func (m *ListAllocationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAllocationsResponse.Marshal(b, m, deterministic)
}
func (m *ListAllocationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAllocationsResponse.Merge(m, src)
}
func (m *ListAllocationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAllocationsResponse.Size(m)
}
func (m *ListAllocationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAllocationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAllocationsResponse proto.InternalMessageInfo

func (m *ListAllocationsResponse) GetAllocations() []*Allocation {
	if m != nil {
		return m.Allocations
	}
	return nil
}

// MARK: list connections request/response
type ListConnectionsResponse struct {
	Total                int32         `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Connections          []*Connection `protobuf:"bytes,2,rep,name=connections,proto3" json:"connections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListConnectionsResponse) Reset()         { *m = ListConnectionsResponse{} }
func (m *ListConnectionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListConnectionsResponse) ProtoMessage()    {}
func (*ListConnectionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{4}
}

func (m *ListConnectionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListConnectionsResponse.Unmarshal(m, b)
}
func (m *ListConnectionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListConnectionsResponse.Marshal(b, m, deterministic)
}
func (m *ListConnectionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListConnectionsResponse.Merge(m, src)
}
func (m *ListConnectionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListConnectionsResponse.Size(m)
}
func (m *ListConnectionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListConnectionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListConnectionsResponse proto.InternalMessageInfo

func (m *ListConnectionsResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListConnectionsResponse) GetConnections() []*Connection {
	if m != nil {
		return m.Connections
	}
	return nil
}

type ListConnectionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListConnectionsRequest) Reset()         { *m = ListConnectionsRequest{} }
func (m *ListConnectionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListConnectionsRequest) ProtoMessage()    {}
func (*ListConnectionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{5}
}

func (m *ListConnectionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListConnectionsRequest.Unmarshal(m, b)
}
func (m *ListConnectionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListConnectionsRequest.Marshal(b, m, deterministic)
}
func (m *ListConnectionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListConnectionsRequest.Merge(m, src)
}
func (m *ListConnectionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListConnectionsRequest.Size(m)
}
func (m *ListConnectionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListConnectionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListConnectionsRequest proto.InternalMessageInfo

// MARK: authenticate request/response
type AuthenticateRequest struct {
	File                 string   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Client               string   `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	ConnectingIp         string   `protobuf:"bytes,3,opt,name=connecting_ip,json=connectingIp,proto3" json:"connecting_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{6}
}

func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(m, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *AuthenticateRequest) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *AuthenticateRequest) GetConnectingIp() string {
	if m != nil {
		return m.ConnectingIp
	}
	return ""
}

type AuthenticateResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{7}
}

func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(m, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// MARK: connection
type Connection struct {
	Client               string      `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Username             string      `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Allocation           *Allocation `protobuf:"bytes,3,opt,name=allocation,proto3" json:"allocation,omitempty"`
	Routes               []*Route    `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty"`
	Since                int64       `protobuf:"varint,5,opt,name=since,proto3" json:"since,omitempty"`
	ConnectingIp         string      `protobuf:"bytes,6,opt,name=connecting_ip,json=connectingIp,proto3" json:"connecting_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{8}
}

func (m *Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connection.Unmarshal(m, b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
}
func (m *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(m, src)
}
func (m *Connection) XXX_Size() int {
	return xxx_messageInfo_Connection.Size(m)
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *Connection) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Connection) GetAllocation() *Allocation {
	if m != nil {
		return m.Allocation
	}
	return nil
}

func (m *Connection) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

func (m *Connection) GetSince() int64 {
	if m != nil {
		return m.Since
	}
	return 0
}

func (m *Connection) GetConnectingIp() string {
	if m != nil {
		return m.ConnectingIp
	}
	return ""
}

// MARK: allocation
type Allocation struct {
	Client               string   `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Allocation) Reset()         { *m = Allocation{} }
func (m *Allocation) String() string { return proto.CompactTextString(m) }
func (*Allocation) ProtoMessage()    {}
func (*Allocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{9}
}

func (m *Allocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Allocation.Unmarshal(m, b)
}
func (m *Allocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Allocation.Marshal(b, m, deterministic)
}
func (m *Allocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Allocation.Merge(m, src)
}
func (m *Allocation) XXX_Size() int {
	return xxx_messageInfo_Allocation.Size(m)
}
func (m *Allocation) XXX_DiscardUnknown() {
	xxx_messageInfo_Allocation.DiscardUnknown(m)
}

var xxx_messageInfo_Allocation proto.InternalMessageInfo

func (m *Allocation) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *Allocation) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

// MARK: Route
type Route struct {
	Cidr                 string   `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{10}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetCidr() string {
	if m != nil {
		return m.Cidr
	}
	return ""
}

// MARK: create client request/response
type CreateClientRequest struct {
	Client               string   `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Force                bool     `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClientRequest) Reset()         { *m = CreateClientRequest{} }
func (m *CreateClientRequest) String() string { return proto.CompactTextString(m) }
func (*CreateClientRequest) ProtoMessage()    {}
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{11}
}

func (m *CreateClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientRequest.Unmarshal(m, b)
}
func (m *CreateClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientRequest.Marshal(b, m, deterministic)
}
func (m *CreateClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientRequest.Merge(m, src)
}
func (m *CreateClientRequest) XXX_Size() int {
	return xxx_messageInfo_CreateClientRequest.Size(m)
}
func (m *CreateClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientRequest proto.InternalMessageInfo

func (m *CreateClientRequest) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *CreateClientRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type CreateClientResponse struct {
	Config               string   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClientResponse) Reset()         { *m = CreateClientResponse{} }
func (m *CreateClientResponse) String() string { return proto.CompactTextString(m) }
func (*CreateClientResponse) ProtoMessage()    {}
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{12}
}

func (m *CreateClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientResponse.Unmarshal(m, b)
}
func (m *CreateClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientResponse.Marshal(b, m, deterministic)
}
func (m *CreateClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientResponse.Merge(m, src)
}
func (m *CreateClientResponse) XXX_Size() int {
	return xxx_messageInfo_CreateClientResponse.Size(m)
}
func (m *CreateClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientResponse proto.InternalMessageInfo

func (m *CreateClientResponse) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

// MARK: get client request/response
type GetClientRequest struct {
	Client               string   `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientRequest) Reset()         { *m = GetClientRequest{} }
func (m *GetClientRequest) String() string { return proto.CompactTextString(m) }
func (*GetClientRequest) ProtoMessage()    {}
func (*GetClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{13}
}

func (m *GetClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientRequest.Unmarshal(m, b)
}
func (m *GetClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientRequest.Marshal(b, m, deterministic)
}
func (m *GetClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientRequest.Merge(m, src)
}
func (m *GetClientRequest) XXX_Size() int {
	return xxx_messageInfo_GetClientRequest.Size(m)
}
func (m *GetClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientRequest proto.InternalMessageInfo

func (m *GetClientRequest) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

type GetClientResponse struct {
	Status               ClientStatus `protobuf:"varint,1,opt,name=status,proto3,enum=protobuf.ClientStatus" json:"status,omitempty"`
	ExpiresDate          int64        `protobuf:"varint,2,opt,name=expires_date,json=expiresDate,proto3" json:"expires_date,omitempty"`
	RevocationDate       int64        `protobuf:"varint,3,opt,name=revocation_date,json=revocationDate,proto3" json:"revocation_date,omitempty"`
	Config               string       `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetClientResponse) Reset()         { *m = GetClientResponse{} }
func (m *GetClientResponse) String() string { return proto.CompactTextString(m) }
func (*GetClientResponse) ProtoMessage()    {}
func (*GetClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{14}
}

func (m *GetClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientResponse.Unmarshal(m, b)
}
func (m *GetClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientResponse.Marshal(b, m, deterministic)
}
func (m *GetClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientResponse.Merge(m, src)
}
func (m *GetClientResponse) XXX_Size() int {
	return xxx_messageInfo_GetClientResponse.Size(m)
}
func (m *GetClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientResponse proto.InternalMessageInfo

func (m *GetClientResponse) GetStatus() ClientStatus {
	if m != nil {
		return m.Status
	}
	return ClientStatus_EXPIRED
}

func (m *GetClientResponse) GetExpiresDate() int64 {
	if m != nil {
		return m.ExpiresDate
	}
	return 0
}

func (m *GetClientResponse) GetRevocationDate() int64 {
	if m != nil {
		return m.RevocationDate
	}
	return 0
}

func (m *GetClientResponse) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

// MARK: revoke client request/response
type RevokeClientRequest struct {
	Client               string   `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeClientRequest) Reset()         { *m = RevokeClientRequest{} }
func (m *RevokeClientRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeClientRequest) ProtoMessage()    {}
func (*RevokeClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{15}
}

func (m *RevokeClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeClientRequest.Unmarshal(m, b)
}
func (m *RevokeClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeClientRequest.Marshal(b, m, deterministic)
}
func (m *RevokeClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeClientRequest.Merge(m, src)
}
func (m *RevokeClientRequest) XXX_Size() int {
	return xxx_messageInfo_RevokeClientRequest.Size(m)
}
func (m *RevokeClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeClientRequest proto.InternalMessageInfo

func (m *RevokeClientRequest) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

type RevokeClientResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeClientResponse) Reset()         { *m = RevokeClientResponse{} }
func (m *RevokeClientResponse) String() string { return proto.CompactTextString(m) }
func (*RevokeClientResponse) ProtoMessage()    {}
func (*RevokeClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{16}
}

func (m *RevokeClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeClientResponse.Unmarshal(m, b)
}
func (m *RevokeClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeClientResponse.Marshal(b, m, deterministic)
}
func (m *RevokeClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeClientResponse.Merge(m, src)
}
func (m *RevokeClientResponse) XXX_Size() int {
	return xxx_messageInfo_RevokeClientResponse.Size(m)
}
func (m *RevokeClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeClientResponse proto.InternalMessageInfo

func (m *RevokeClientResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

// MARK: list clients request/response
type ListClientsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListClientsRequest) Reset()         { *m = ListClientsRequest{} }
func (m *ListClientsRequest) String() string { return proto.CompactTextString(m) }
func (*ListClientsRequest) ProtoMessage()    {}
func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{17}
}

func (m *ListClientsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClientsRequest.Unmarshal(m, b)
}
func (m *ListClientsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClientsRequest.Marshal(b, m, deterministic)
}
func (m *ListClientsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClientsRequest.Merge(m, src)
}
func (m *ListClientsRequest) XXX_Size() int {
	return xxx_messageInfo_ListClientsRequest.Size(m)
}
func (m *ListClientsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClientsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListClientsRequest proto.InternalMessageInfo

type ListClientsResponse struct {
	Clients              []*Client `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListClientsResponse) Reset()         { *m = ListClientsResponse{} }
func (m *ListClientsResponse) String() string { return proto.CompactTextString(m) }
func (*ListClientsResponse) ProtoMessage()    {}
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{18}
}

func (m *ListClientsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListClientsResponse.Unmarshal(m, b)
}
func (m *ListClientsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListClientsResponse.Marshal(b, m, deterministic)
}
func (m *ListClientsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListClientsResponse.Merge(m, src)
}
func (m *ListClientsResponse) XXX_Size() int {
	return xxx_messageInfo_ListClientsResponse.Size(m)
}
func (m *ListClientsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListClientsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListClientsResponse proto.InternalMessageInfo

func (m *ListClientsResponse) GetClients() []*Client {
	if m != nil {
		return m.Clients
	}
	return nil
}

type Client struct {
	Status               ClientStatus `protobuf:"varint,1,opt,name=status,proto3,enum=protobuf.ClientStatus" json:"status,omitempty"`
	ExpiresDate          int64        `protobuf:"varint,2,opt,name=expires_date,json=expiresDate,proto3" json:"expires_date,omitempty"`
	RevocationDate       int64        `protobuf:"varint,3,opt,name=revocation_date,json=revocationDate,proto3" json:"revocation_date,omitempty"`
	Client               string       `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ed45b80aaca82a7, []int{19}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetStatus() ClientStatus {
	if m != nil {
		return m.Status
	}
	return ClientStatus_EXPIRED
}

func (m *Client) GetExpiresDate() int64 {
	if m != nil {
		return m.ExpiresDate
	}
	return 0
}

func (m *Client) GetRevocationDate() int64 {
	if m != nil {
		return m.RevocationDate
	}
	return 0
}

func (m *Client) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func init() {
	proto.RegisterEnum("protobuf.ClientStatus", ClientStatus_name, ClientStatus_value)
	proto.RegisterType((*DisconnectRequest)(nil), "protobuf.DisconnectRequest")
	proto.RegisterType((*DisconnectResponse)(nil), "protobuf.DisconnectResponse")
	proto.RegisterType((*ListAllocationsRequest)(nil), "protobuf.ListAllocationsRequest")
	proto.RegisterType((*ListAllocationsResponse)(nil), "protobuf.ListAllocationsResponse")
	proto.RegisterType((*ListConnectionsResponse)(nil), "protobuf.ListConnectionsResponse")
	proto.RegisterType((*ListConnectionsRequest)(nil), "protobuf.ListConnectionsRequest")
	proto.RegisterType((*AuthenticateRequest)(nil), "protobuf.AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "protobuf.AuthenticateResponse")
	proto.RegisterType((*Connection)(nil), "protobuf.Connection")
	proto.RegisterType((*Allocation)(nil), "protobuf.Allocation")
	proto.RegisterType((*Route)(nil), "protobuf.Route")
	proto.RegisterType((*CreateClientRequest)(nil), "protobuf.CreateClientRequest")
	proto.RegisterType((*CreateClientResponse)(nil), "protobuf.CreateClientResponse")
	proto.RegisterType((*GetClientRequest)(nil), "protobuf.GetClientRequest")
	proto.RegisterType((*GetClientResponse)(nil), "protobuf.GetClientResponse")
	proto.RegisterType((*RevokeClientRequest)(nil), "protobuf.RevokeClientRequest")
	proto.RegisterType((*RevokeClientResponse)(nil), "protobuf.RevokeClientResponse")
	proto.RegisterType((*ListClientsRequest)(nil), "protobuf.ListClientsRequest")
	proto.RegisterType((*ListClientsResponse)(nil), "protobuf.ListClientsResponse")
	proto.RegisterType((*Client)(nil), "protobuf.Client")
}

func init() { proto.RegisterFile("vpn_service.proto", fileDescriptor_9ed45b80aaca82a7) }

var fileDescriptor_9ed45b80aaca82a7 = []byte{
	// 741 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xf9, 0x6b, 0x3b, 0x49, 0xd3, 0x74, 0x13, 0x15, 0xcb, 0x6d, 0x51, 0x6a, 0x84, 0x1a,
	0x15, 0xc8, 0xa1, 0xad, 0xb8, 0x47, 0x49, 0x54, 0x15, 0x0a, 0x94, 0xad, 0x14, 0xb8, 0x45, 0xae,
	0xbb, 0x29, 0x2b, 0x82, 0x6d, 0xec, 0x4d, 0x04, 0x77, 0x1e, 0x83, 0x3b, 0xef, 0xc4, 0xd3, 0x20,
	0xef, 0xae, 0xb3, 0x6b, 0xc7, 0x21, 0xbd, 0x71, 0x4a, 0x76, 0xe6, 0xf3, 0x37, 0x33, 0xdf, 0xec,
	0xcc, 0xc2, 0xee, 0x3c, 0xf0, 0xc6, 0x11, 0x09, 0xe7, 0xd4, 0x25, 0xdd, 0x20, 0xf4, 0x99, 0x8f,
	0x36, 0xf9, 0xcf, 0xed, 0x6c, 0x62, 0x3f, 0x87, 0xdd, 0x01, 0x8d, 0x5c, 0xdf, 0xf3, 0x88, 0xcb,
	0x30, 0xf9, 0x36, 0x23, 0x11, 0x43, 0x7b, 0x50, 0x71, 0xa7, 0x94, 0x78, 0xcc, 0x34, 0xda, 0x46,
	0x67, 0x0b, 0xcb, 0x93, 0xfd, 0x02, 0x90, 0x0e, 0x8e, 0x02, 0xdf, 0x8b, 0x48, 0x8c, 0x8e, 0x98,
	0xc3, 0x66, 0x11, 0x47, 0x97, 0xb1, 0x3c, 0xd9, 0x1f, 0x61, 0xef, 0x8a, 0x46, 0xac, 0x37, 0x9d,
	0xfa, 0xae, 0xc3, 0xa8, 0xef, 0x45, 0x6b, 0xf8, 0xd1, 0x33, 0xa8, 0xfb, 0xde, 0xf4, 0xc7, 0xd8,
	0x11, 0x9f, 0x90, 0x3b, 0xb3, 0xd0, 0x36, 0x3a, 0x9b, 0x78, 0x3b, 0xb6, 0xf6, 0x12, 0xa3, 0xfd,
	0x01, 0x1e, 0x2f, 0x11, 0xcb, 0x5c, 0x5e, 0x41, 0xd5, 0x51, 0x66, 0xd3, 0x68, 0x17, 0x3b, 0xd5,
	0xd3, 0x56, 0x37, 0x29, 0xb7, 0xab, 0xbe, 0xc1, 0x3a, 0xd0, 0xbe, 0x17, 0x94, 0x7d, 0x51, 0x5a,
	0x8a, 0xb2, 0x05, 0x65, 0xe6, 0x33, 0x67, 0x2a, 0xab, 0x13, 0x87, 0x38, 0x90, 0xab, 0xc0, 0x66,
	0x21, 0x1b, 0x48, 0x31, 0x61, 0x1d, 0x68, 0x9b, 0x42, 0x94, 0x54, 0x20, 0x2e, 0x8a, 0x3d, 0x81,
	0x66, 0x6f, 0xc6, 0x3e, 0x13, 0x8f, 0xd1, 0xb8, 0xcc, 0x44, 0x2b, 0x04, 0xa5, 0x09, 0x9d, 0x12,
	0xa9, 0x14, 0xff, 0xaf, 0xe9, 0x57, 0x48, 0xe9, 0xf7, 0x14, 0xb6, 0x93, 0x58, 0xde, 0xfd, 0x98,
	0x06, 0x66, 0x91, 0xbb, 0x6b, 0xca, 0x78, 0x19, 0xd8, 0x5d, 0x68, 0xa5, 0xe3, 0xac, 0x69, 0xe3,
	0x1f, 0x03, 0x40, 0xa5, 0xbb, 0xb2, 0x77, 0x16, 0x6c, 0xce, 0x22, 0x12, 0x7a, 0xce, 0x57, 0x22,
	0xb3, 0x5a, 0x9c, 0xd1, 0x39, 0x80, 0x12, 0x9b, 0x27, 0xb5, 0xaa, 0x29, 0x1a, 0x0e, 0x1d, 0x43,
	0x25, 0xf4, 0x67, 0x8c, 0x44, 0x66, 0x89, 0xab, 0xbb, 0xa3, 0xbe, 0xc0, 0xb1, 0x1d, 0x4b, 0x77,
	0xdc, 0xa1, 0x88, 0x7a, 0x2e, 0x31, 0xcb, 0x6d, 0xa3, 0x53, 0xc4, 0xe2, 0xb0, 0x2c, 0x46, 0x25,
	0x47, 0x8c, 0x73, 0x00, 0x15, 0x7d, 0x65, 0x6d, 0x75, 0x28, 0xd0, 0x40, 0x56, 0x55, 0xa0, 0x81,
	0xbd, 0x0f, 0x65, 0x9e, 0x41, 0xdc, 0x1c, 0x97, 0xde, 0x85, 0x49, 0x73, 0xe2, 0xff, 0x76, 0x1f,
	0x9a, 0xfd, 0x90, 0x38, 0x8c, 0xf4, 0xf9, 0xc7, 0xeb, 0xee, 0x7c, 0x0b, 0xca, 0x13, 0x3f, 0x74,
	0x89, 0xbc, 0xea, 0xe2, 0x10, 0x37, 0x29, 0x4d, 0xa2, 0x9a, 0xe4, 0xfa, 0xde, 0x84, 0xde, 0x2f,
	0x58, 0xf8, 0xc9, 0x3e, 0x81, 0xc6, 0x05, 0x61, 0x0f, 0x8a, 0x68, 0xff, 0x36, 0x60, 0x57, 0x03,
	0x4b, 0xe6, 0x6e, 0xaa, 0xfd, 0xf5, 0xd3, 0x3d, 0xed, 0x2e, 0x73, 0xe4, 0x0d, 0xf7, 0x26, 0xd7,
	0x02, 0x1d, 0x41, 0x8d, 0x7c, 0x0f, 0x68, 0x48, 0xa2, 0xf1, 0x9d, 0xc3, 0x44, 0xfa, 0x45, 0x5c,
	0x95, 0xb6, 0x81, 0xc3, 0x08, 0x3a, 0x86, 0x9d, 0x90, 0xcc, 0xa5, 0xb8, 0x02, 0x55, 0xe4, 0xa8,
	0xba, 0x32, 0x73, 0xa0, 0xaa, 0xaa, 0x94, 0xaa, 0xea, 0x25, 0x34, 0x31, 0x99, 0xfb, 0x5f, 0x1e,
	0x26, 0x65, 0x2c, 0x5a, 0x1a, 0xbe, 0xe6, 0x66, 0xb7, 0x00, 0xf1, 0x59, 0xe4, 0xe8, 0xc5, 0x1c,
	0xf6, 0xa0, 0x99, 0xb2, 0x4a, 0x92, 0x13, 0xd8, 0x10, 0x61, 0x92, 0xad, 0xd2, 0xc8, 0x0a, 0x84,
	0x13, 0x80, 0xfd, 0xcb, 0x80, 0x8a, 0xb0, 0xfd, 0x77, 0x59, 0x85, 0x4e, 0x25, 0x5d, 0xa7, 0x93,
	0x33, 0xa8, 0xe9, 0xb1, 0x51, 0x15, 0x36, 0x86, 0x9f, 0xae, 0x2f, 0xf1, 0x70, 0xd0, 0x78, 0x84,
	0xb6, 0xa0, 0x3c, 0xea, 0x5d, 0x5d, 0x0e, 0x1a, 0x46, 0x6c, 0xc7, 0xc3, 0xd1, 0xfb, 0x37, 0xc3,
	0x41, 0xa3, 0x70, 0xfa, 0xb3, 0x0c, 0x30, 0xba, 0x7e, 0x77, 0x23, 0xde, 0x11, 0x34, 0x82, 0x9d,
	0xcc, 0x1e, 0x43, 0x6d, 0x55, 0x5a, 0xfe, 0x8a, 0xb3, 0x8e, 0xfe, 0x81, 0x90, 0x32, 0x4b, 0x5e,
	0x6d, 0xb7, 0x67, 0x79, 0x97, 0xdf, 0x93, 0x2c, 0x6f, 0xde, 0xc3, 0x70, 0x01, 0xa0, 0x9e, 0x2e,
	0xb4, 0xaf, 0x3e, 0x58, 0x7a, 0xfd, 0xac, 0x83, 0x7c, 0xa7, 0x24, 0x7a, 0x0b, 0x35, 0x7d, 0x7d,
	0xa2, 0x43, 0x6d, 0x8f, 0x2d, 0xaf, 0x6f, 0xeb, 0xc9, 0x2a, 0xb7, 0xa2, 0xd3, 0x07, 0x5d, 0xa7,
	0xcb, 0xd9, 0x22, 0x3a, 0x5d, 0xee, 0x7e, 0x18, 0xc0, 0xd6, 0x62, 0xb4, 0x91, 0xa5, 0xc0, 0xd9,
	0xe5, 0x60, 0xed, 0xe7, 0xfa, 0x54, 0x52, 0xfa, 0x20, 0xe9, 0x49, 0xe5, 0xcc, 0xa3, 0x9e, 0x54,
	0xee, 0xfc, 0xbd, 0x86, 0xaa, 0x36, 0x51, 0xe8, 0x20, 0x73, 0x0b, 0x52, 0xe3, 0x67, 0x1d, 0xae,
	0xf0, 0x0a, 0xae, 0xdb, 0x0a, 0xf7, 0x9e, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x50, 0xc9, 0x95,
	0x90, 0xd5, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VPNServiceClient is the client API for VPNService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VPNServiceClient interface {
	ListConnections(ctx context.Context, in *ListConnectionsRequest, opts ...grpc.CallOption) (*ListConnectionsResponse, error)
	ListAllocations(ctx context.Context, in *ListAllocationsRequest, opts ...grpc.CallOption) (*ListAllocationsResponse, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error)
	GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*GetClientResponse, error)
	RevokeClient(ctx context.Context, in *RevokeClientRequest, opts ...grpc.CallOption) (*RevokeClientResponse, error)
	ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error)
}

type vPNServiceClient struct {
	cc *grpc.ClientConn
}

func NewVPNServiceClient(cc *grpc.ClientConn) VPNServiceClient {
	return &vPNServiceClient{cc}
}

func (c *vPNServiceClient) ListConnections(ctx context.Context, in *ListConnectionsRequest, opts ...grpc.CallOption) (*ListConnectionsResponse, error) {
	out := new(ListConnectionsResponse)
	err := c.cc.Invoke(ctx, "/protobuf.VPNService/ListConnections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) ListAllocations(ctx context.Context, in *ListAllocationsRequest, opts ...grpc.CallOption) (*ListAllocationsResponse, error) {
	out := new(ListAllocationsResponse)
	err := c.cc.Invoke(ctx, "/protobuf.VPNService/ListAllocations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, "/protobuf.VPNService/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/protobuf.VPNService/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error) {
	out := new(CreateClientResponse)
	err := c.cc.Invoke(ctx, "/protobuf.VPNService/CreateClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*GetClientResponse, error) {
	out := new(GetClientResponse)
	err := c.cc.Invoke(ctx, "/protobuf.VPNService/GetClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) RevokeClient(ctx context.Context, in *RevokeClientRequest, opts ...grpc.CallOption) (*RevokeClientResponse, error) {
	out := new(RevokeClientResponse)
	err := c.cc.Invoke(ctx, "/protobuf.VPNService/RevokeClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vPNServiceClient) ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error) {
	out := new(ListClientsResponse)
	err := c.cc.Invoke(ctx, "/protobuf.VPNService/ListClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VPNServiceServer is the server API for VPNService service.
type VPNServiceServer interface {
	ListConnections(context.Context, *ListConnectionsRequest) (*ListConnectionsResponse, error)
	ListAllocations(context.Context, *ListAllocationsRequest) (*ListAllocationsResponse, error)
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error)
	GetClient(context.Context, *GetClientRequest) (*GetClientResponse, error)
	RevokeClient(context.Context, *RevokeClientRequest) (*RevokeClientResponse, error)
	ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error)
}

// UnimplementedVPNServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVPNServiceServer struct {
}

func (*UnimplementedVPNServiceServer) ListConnections(ctx context.Context, req *ListConnectionsRequest) (*ListConnectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConnections not implemented")
}
func (*UnimplementedVPNServiceServer) ListAllocations(ctx context.Context, req *ListAllocationsRequest) (*ListAllocationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllocations not implemented")
}
func (*UnimplementedVPNServiceServer) Disconnect(ctx context.Context, req *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (*UnimplementedVPNServiceServer) Authenticate(ctx context.Context, req *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (*UnimplementedVPNServiceServer) CreateClient(ctx context.Context, req *CreateClientRequest) (*CreateClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClient not implemented")
}
func (*UnimplementedVPNServiceServer) GetClient(ctx context.Context, req *GetClientRequest) (*GetClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClient not implemented")
}
func (*UnimplementedVPNServiceServer) RevokeClient(ctx context.Context, req *RevokeClientRequest) (*RevokeClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeClient not implemented")
}
func (*UnimplementedVPNServiceServer) ListClients(ctx context.Context, req *ListClientsRequest) (*ListClientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClients not implemented")
}

func RegisterVPNServiceServer(s *grpc.Server, srv VPNServiceServer) {
	s.RegisterService(&_VPNService_serviceDesc, srv)
}

func _VPNService_ListConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).ListConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.VPNService/ListConnections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).ListConnections(ctx, req.(*ListConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_ListAllocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).ListAllocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.VPNService/ListAllocations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).ListAllocations(ctx, req.(*ListAllocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.VPNService/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.VPNService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.VPNService/CreateClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).CreateClient(ctx, req.(*CreateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_GetClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).GetClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.VPNService/GetClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).GetClient(ctx, req.(*GetClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_RevokeClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).RevokeClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.VPNService/RevokeClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).RevokeClient(ctx, req.(*RevokeClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VPNService_ListClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VPNServiceServer).ListClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.VPNService/ListClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VPNServiceServer).ListClients(ctx, req.(*ListClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VPNService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.VPNService",
	HandlerType: (*VPNServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListConnections",
			Handler:    _VPNService_ListConnections_Handler,
		},
		{
			MethodName: "ListAllocations",
			Handler:    _VPNService_ListAllocations_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _VPNService_Disconnect_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _VPNService_Authenticate_Handler,
		},
		{
			MethodName: "CreateClient",
			Handler:    _VPNService_CreateClient_Handler,
		},
		{
			MethodName: "GetClient",
			Handler:    _VPNService_GetClient_Handler,
		},
		{
			MethodName: "RevokeClient",
			Handler:    _VPNService_RevokeClient_Handler,
		},
		{
			MethodName: "ListClients",
			Handler:    _VPNService_ListClients_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vpn_service.proto",
}
